### ISSUE TITLE
[BUG] Message query by ID fails in latest master branch (2025-03-28)

### ISSUE THREAD

**Issue by Crazylychee** [apache/rocketmq-dashboard#274]
- **Environment**
  rocketmq 5.3.0 and  rocketmq 5.3.2
  rocketmq dashboard image latest
  rocketmq source latest
  docker 26.1.4
  centos 7.6

- **Deployment**
docker-compose
```yml
version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.3.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.3.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
#    environment:
#      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq
    command: sh mqbroker -c /home/rocketmq/rocketmq/conf/broker.conf
    volumes:
      - /opt/rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq/conf/broker.conf
      - /opt/rocketmq/broker/data:/home/rocketmq/store 
      - /opt/rocketmq/broker/logs:/home/rocketmq/logs 
  console:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-console
    ports:
      - "8083:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Drocketmq.config.proxyAddr=rmqnamesrv:8080 -Drocketmq.config.proxyAddrs=rmqnamesrv:8080
    networks:
      - rocketmq
    depends_on:
      - namesrv
      - broker
  proxy:
    image: apache/rocketmq:5.3.0
    container_name: rmqproxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy
networks:
  rocketmq:
    driver: bridge


```

- **Issue Description**
While using the latest source code to build and deploy a Docker image, I suddenly noticed that querying messages by their message ID would result in errors. This issue occurs consistently—whether running on Windows or Linux (AMD).
![Image](https://github.com/user-attachments/assets/de5618f5-22f5-4491-8481-8abbae65ab16)
However, when using the official Docker image (the one that hasn't been updated in a long time), this problem does not occur. After rolling back the code to a version before the changes made on 2024-09-07 19:59, the issue was resolved.
